CREATE TABLE IF NOT EXISTS "accounts" (
  "_id" INTEGER NOT NULL UNIQUE,
  "username" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "password" TEXT NOT NULL,
  "isAdmin" INTEGER DEFAULT 0,
  UNIQUE (username COLLATE NOCASE),
  PRIMARY KEY("id" AUTOINCREMENT)
);
