CREATE TABLE IF NOT EXISTS "albums" (
  "_id" INTEGER NOT NULL UNIQUE,
  "id" TEXT NOT NULL UNIQUE,
  "title" TEXT NOT NULL,
  "uploaded_at" TEXT NOT NULL,
  "uploaded_by" TEXT NOT NULL DEFAULT "SYSTEM",
  "ttl" INTEGER,
  "isPrivate" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY("_id" AUTOINCREMENT)
);
